import Sidebar from "@/components/Sidebar";
import { ReactNode } from "react";
import { getServerSession } from "next-auth";
import { notFound } from "next/navigation";
import { fetchRedis } from "@/lib/helpers/redis";
import { authOptions } from "@/lib/auth";
import { getFriendsByUserId } from "@/lib/helpers/getFriendsByUserId";

export const metadata = {
  title: "Dashboard | Whisper Wire",
  description: "Generated by create next app",
};

interface layoutProps {
  children: ReactNode;
}

const Layout = async ({ children }: layoutProps) => {
  const session = await getServerSession(authOptions);

  if (!session) notFound();

  const friends = await getFriendsByUserId(session.user.id);

  const unseenRequestCount = (
    (await fetchRedis(
      "smembers",
      `user:${session.user.id}:incoming_friend_requests`
    )) as User[]
  ).length;

  return (
    <div className="relative flex h-screen w-full flex-col overflow-hidden sm:flex-row ">
      <Sidebar
        initialUnseenRequestsCount={unseenRequestCount}
        session={session as any}
        friends={friends}
      />
      <div className="h-[91%] w-full sm:flex-[0.70] lg:flex-[0.75]">
        {children}
      </div>
    </div>
  );
};

export default Layout;
