import Provider from "@/components/Provider";
import "./globals.css";

export const metadata = {
  title: "Whisper Wire",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-gray-200">
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
