export const metadata = {
  title: "Login | Whisper Wire",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <div className=" ">{children}</div>;
}
