import Sidebar from "@/components/Sidebar";
import { FC, ReactNode } from "react";

export const metadata = {
  title: "Dashboard | Whisper Wire",
  description: "Generated by create next app",
};

interface layoutProps {
  children: ReactNode;
}

const Layout = async ({ children }: layoutProps) => {
  return (
    <div className="w-full h-screen flex relative">
      <Sidebar />
      <div className="sm:flex-[0.70] lg:flex-[0.75]">{children}</div>
    </div>
  );
};

export default Layout;
