import Sidebar from "@/components/Sidebar";
import { FC, ReactNode } from "react";

export const metadata = {
  title: "Dashboard | Whisper Wire",
  description: "Generated by create next app",
};

interface layoutProps {
  children: ReactNode;
}

const Layout = async ({ children }: layoutProps) => {
  return (
    <div className="relative flex h-screen w-full flex-col overflow-hidden sm:flex-row">
      <Sidebar />
      <div className="w-full bg-red-500 sm:flex-[0.70] lg:flex-[0.75]">
        {children}
      </div>
    </div>
  );
};

export default Layout;
